services:
  - type: web
    name: sea-crest-trading-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: hypercorn flask_app:app
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
    runtime: python3
    plan: free